@host=http://localhost:3000/v1
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDcwYTZjOTliNjk1NGYyOTIwMjZlYSIsImVtYWlsIjoiYTRAYi5jb20iLCJmaXJzdE5hbWUiOiJBIiwibGFzdE5hbWUiOiJCIiwiaW1hZ2UiOm51bGwsImJpcnRoRGF0ZSI6bnVsbCwicm9sZSI6IlVTRVIiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwic2Vzc2lvbiI6IjYyMDdjZDUzNjc3NmYxNzRjYWVjODZlZCIsImlhdCI6MTY0NDY3ODQ4MywiZXhwIjoxNjQ0Njc5MzgzfQ.EuVMJQ-TS-rZWtmN829iv9oNy52WSkl_t3VGUllQe9LCSP__c38dBOk426IalTETlVX8RixEQJv78QCpdF98rc8NcRVKuTkp9y5uDeZhlS_hu64HFMOX4pSicOa5j6wROo4GksEIPCLHUGT8CC6JPv7jkUdH1oBv740_vEgU73g

@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDcwYTZjOTliNjk1NGYyOTIwMjZlYSIsImVtYWlsIjoiYTRAYi5jb20iLCJmaXJzdE5hbWUiOiJBIiwibGFzdE5hbWUiOiJCIiwiaW1hZ2UiOm51bGwsImJpcnRoRGF0ZSI6bnVsbCwicm9sZSI6IlVTRVIiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwic2Vzc2lvbiI6IjYyMDdjZDUzNjc3NmYxNzRjYWVjODZlZCIsImlhdCI6MTY0NDY3ODQ4MywiZXhwIjoxNjc2MjM2MDgzfQ.LXsJBV0D5bXPWcTBY6xKx8lG43SmR_B7Nii9aqxLFXDhaZ1jZB49_rML-2JA3cIiskSzadICpxAM3AZnmV01qPZlD_BjjtJacEMz5lAhEyiIyCJyarzKz7XLD7n6mWaPrVWJO_J7C1rvtda6IhU-ZhV9tRP6CG38puhFyoLI6uE



POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "a4@b.com",
    "password": "Abcd1234!",
    "passwordConfirmation": "Abcd1234!",
    "firstName": "A",
    "lastName": "B"
}

###


POST {{host}}/auth/create-admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "a6@b.com",
    "password": "Abcd1234!",
    "passwordConfirmation": "Abcd1234!",
    "firstName": "A",
    "lastName": "B"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "a4@b.com",
    "password": "Abcd1234!"
}

###

POST {{host}}/auth/forgot-password
Content-Type: application/json

{
  "email": "a1@b.com"
}

###

POST {{host}}/auth/reset-password/j1t8y0sbni4admlv6fipw87veqc505qcvcr2ujqa
Content-Type: application/json

{
  "password": "Abcd1234!",
  "passwordConfirmation": "Abcd1234!"
}

###

POST {{host}}/auth/change-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "Abcd1234!2",
  "passwordConfirmation": "Abcd1234!2"
}