@host=http://localhost:3000/v1
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDcwYTZjOTliNjk1NGYyOTIwMjZlYSIsImVtYWlsIjoiYTRAYi5jb20iLCJmaXJzdE5hbWUiOiJBIiwibGFzdE5hbWUiOiJCIiwiaW1hZ2UiOm51bGwsImJpcnRoRGF0ZSI6bnVsbCwicm9sZSI6IlVTRVIiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwic2Vzc2lvbiI6IjYyMDgxNjM0ZDRmN2M3ZGVlMTZlMzFlNiIsImlhdCI6MTY0NDY5NzE0MCwiZXhwIjoxNjQ1MzAxOTQwfQ.XDr4YuwNaLagjdnFuj2vZKeTFKz9_222TgrpYwiMk2ofLgDMLF0AS6jCC3VdTBNoSwK7DMDtHwcqLRNcp1lS4mIkKrepG5bwgxD6_nS0jJsrFg9wlDaKuDGlbj1qX_cC5qf5vNYZKfjlBe8k-adRQvp1JDtw7zpbiqsJRajGxdI

@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDcwYTZjOTliNjk1NGYyOTIwMjZlYSIsImVtYWlsIjoiYTRAYi5jb20iLCJmaXJzdE5hbWUiOiJBIiwibGFzdE5hbWUiOiJCIiwiaW1hZ2UiOm51bGwsImJpcnRoRGF0ZSI6bnVsbCwicm9sZSI6IlVTRVIiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0xMlQwMToxNjoyOC45ODVaIiwic2Vzc2lvbiI6IjYyMDgxNjM0ZDRmN2M3ZGVlMTZlMzFlNiIsImlhdCI6MTY0NDY5NzE0MCwiZXhwIjoxNjc2MjU0NzQwfQ.M5gHWRjmuaDdmlDGnz14MSeTRfYlL4xL8bFxR4EKZWPshYMaEMql0Qlae2fTNxa6ryViqsYBayud63H--1DzFk5zJ7gyGHHdfm_YIIzFxJeBP9wBFZta5-kpDWMIRO3bBS4ZhsD9GtSXg2wUmgXgZopGPHh8h7NxA5k_T-Me7Rs



POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "a2@b.com",
  "password": "Abcd1234!",
  "passwordConfirmation": "Abcd1234!",
  "firstName": "A",
  "lastName": "B"
}

###


POST {{host}}/auth/create-first-admin
Content-Type: application/json

{
  "email": "a@b.com",
  "password": "Abcd1234!",
  "passwordConfirmation": "Abcd1234!",
  "firstName": "A",
  "lastName": "B"
}

###


POST {{host}}/auth/create-admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "a@b.com",
    "password": "Abcd1234!",
    "passwordConfirmation": "Abcd1234!",
    "firstName": "A",
    "lastName": "B"
}

### LOGIN

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "a4@b.com",
    "password": "Abcd1234!"
}

###

POST {{host}}/auth/forgot-password
Content-Type: application/json

{
  "email": "a1@b.com"
}

###

POST {{host}}/auth/reset-password/r1wm2vbeax239csn7roepf2seq9e636q87uoy1zk
Content-Type: application/json

{
  "password": "Abcd1234!",
  "passwordConfirmation": "Abcd1234!"
}

###

POST {{host}}/auth/change-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "Abcd1234!2",
  "passwordConfirmation": "Abcd1234!2"
}

###

POST {{host}}/auth/change-email/60f335bf00b32ef000bd9a94/confirm/kpzsaaq2l28o1y8b5zdzjb85i6acve1z1pa702z5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

POST {{host}}/auth/change-email/60f335bf00b32ef000bd9a94
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "a1@b.com"
}