@host=http://localhost:3000/api


POST {{host}}/users
Content-Type: application/json

{
  "email": "a4@b.com",
    "password": "Abcd1234!",
    "passwordConfirmation": "Abcd1234!",
    "firstName": "A",
    "lastName": "B"
}

###

POST {{host}}/auth/forgot-password
Content-Type: application/json

{
  "email": "a1@b.com"
}

###

POST {{host}}/auth/reset-password/o5t5wgqb6ft1jx6hm2j92ufqs9rhcmilmkff73z8
Content-Type: application/json

{
  "password": "Abcd1234!",
  "passwordConfirmation": "Abcd1234!"
}