// reads from env vars and overwrites the values provided by config package
export default {
  accessTokenPrivateKey: "ACCESS_TOKEN_PRIVATE_KEY",
  accessTokenPublicKey: "ACCESS_TOKEN_PUBLIC_KEY",
  awsAccessKeyId: "AWS_ACCESS_KEY_ID",
  awsBucketName: "AWS_BUCKET_NAME",
  awsDefaultRegion: "AWS_DEFAULT_REGION",
  awsSecretAccessKey: "AWS_SECRET_ACCESS_KEY",
  dbUri: "DATABASE_URL",
  redisUri: "REDIS_URL",
  redisPassword: "REDIS_PASSWORD",
  emailSenderAddress: "EMAIL_SENDER_ADDRESS",
  emailSenderName: "EMAIL_SENDER_NAME",
  emailSmtpHost: "EMAIL_SMTP_HOST",
  emailSmtpPassword: "EMAIL_SMTP_PASSWORD",
  emailSmtpPort: "EMAIL_SMTP_PORT",
  emailSmtpUser: "EMAIL_SMTP_USER",
  port: "PORT",
  refreshTokenPrivateKey: "REFRESH_PRIVATE_KEY",
  refreshTokenPublicKey: "REFRESH_PUBLIC_KEY",
  stripePublicKey: "STRIPE_PUBLIC_KEY",
  stripeSecretKey: "STRIPE_SECRET_KEY",
  stripeWebhookSecret: "STRIPE_WEBHOOK_SECRET",
};
