export default {
  accessTokenPrivateKey: ``,
  accessTokenPublicKey: ``,
  accessTokenTtl: "15m",
  awsAccessKeyId: '',
  awsSecretAccessKey: '',
  dbUri: "",
  emailSenderAddress: "",
  emailSenderName: "",
  emailSmtpHost: "",
  emailSmtpPassword: "",
  emailSmtpPort: 587,
  emailSmtpUser: "",
  port: 3000,
  refreshTokenPrivateKey: ``,
  refreshTokenPublicKey: ``,
  refreshTokenTtl: "1y",
  saltWorkFactor: 10,
};
