export default {
  accessTokenPrivateKey: ``,
  accessTokenPublicKey: ``,
  accessTokenTtl: "7d",
  awsAccessKeyId: '',
  awsSecretAccessKey: '',
  dbUri: "",
  redisUri: "",
  redisPassword: "",
  emailSenderAddress: "",
  emailSenderName: "",
  emailSmtpHost: "",
  emailSmtpPassword: "",
  emailSmtpPort: 587,
  emailSmtpUser: "",
  frontendBaseUrl: "http://localhost:4200",
  port: 3000,
  refreshTokenPrivateKey: ``,
  refreshTokenPublicKey: ``,
  refreshTokenTtl: "1y",
  saltWorkFactor: 10,
  stripePublicKey: "",
  stripeSecretKey: "",
  stripeWebhookSecret: "",
};
